
services:
  auth_redis:
    container_name: auth_redis
    image: redis:7.0.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - auth_net
    ports:
      - '6379:6379'

  postgres_db:
    container_name: postgres_db
    image: postgres:13-alpine
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
        - ./db.env
    networks:
      - auth_net
    ports:
      - "5432:5432"

  flask_app:
    container_name: flask_app
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - auth_net
    ports:
      - '5000:5000'
    depends_on:
      postgres_db:
        condition: service_healthy
      auth_redis:
        condition: service_started
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    image: nginx:1.23.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
    networks:
      - auth_net
    depends_on:
      - flask_app

volumes:
  postgres_data:

networks:
  auth_net:
